#!/usr/bin/env bash

load_workbench_env() {
  local config_file="${ESPWB_CONFIG_FILE:-config/workbench.env}"
  local name
  declare -A explicit_env=()

  for name in "$@"; do
    if [[ ${!name+x} ]]; then
      explicit_env["$name"]="${!name}"
    fi
  done

  if [[ -r "$config_file" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$config_file"
    set +a
  fi

  for name in "${!explicit_env[@]}"; do
    printf -v "$name" '%s' "${explicit_env[$name]}"
    declare -gx "$name"
  done
}
