substitutions:
  name: magtag-lvgl-shapes
  friendly_name: MagTag LVGL Shapes

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: adafruit_magtag29_esp32s2
  framework:
    type: arduino

logger:
  hardware_uart: USB_CDC

output:
  - platform: gpio
    id: red_led
    pin: GPIO13

interval:
  - interval: 1s
    then:
      - output.turn_on: red_led
      - delay: 500ms
      - output.turn_off: red_led
  - interval: 10s
    then:
      - logger.log: "ping output"

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35

display:
  - platform: waveshare_epaper
    id: magtag_epaper
    cs_pin: GPIO8
    dc_pin: GPIO7
    busy_pin: GPIO5
    reset_pin: GPIO6
    model: gdew029t5
    update_interval: 10s

lvgl:
  displays:
    - magtag_epaper
  rotation: 270
  full_refresh: true
  update_when_display_idle: true
  buffer_size: 100%
  pages:
    - id: shapes_page
      bg_color: white
      widgets:
        - label:
            text: "MagTag LVGL"
            x: 12
            y: 10
            text_color: black
        - obj:
            x: 38
            y: 52
            width: 54
            height: 54
            radius: 27
            bg_opa: 0%
            border_width: 4
            border_color: black
        - obj:
            x: 138
            y: 58
            width: 74
            height: 48
            bg_opa: 0%
            border_width: 4
            border_color: black
            transform_angle: 45deg
        - obj:
            x: 236
            y: 58
            width: 42
            height: 38
            radius: 0
            bg_opa: 0%
            border_width: 4
            border_color: black
