substitutions:
  name: magtag-lvgl-shapes
  friendly_name: MagTag LVGL Shapes

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: adafruit_magtag29_esp32s2
  framework:
    type: arduino

logger:
  hardware_uart: USB_CDC
  level: DEBUG

output:
  - platform: gpio
    id: red_led
    pin: GPIO13

interval:
  - interval: 1s
    then:
      - output.turn_on: red_led
      - delay: 500ms
      - output.turn_off: red_led
  - interval: 10s
    then:
      - logger.log: "ping output"

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35

display:
  - platform: waveshare_epaper
    id: magtag_epaper
    cs_pin: GPIO8
    dc_pin: GPIO7
    busy_pin: GPIO5
    reset_pin: GPIO6
    model: gdew029t5
    auto_clear_enabled: false
    update_interval: never
    full_update_every: 1

lvgl:
  displays:
    - magtag_epaper
  full_refresh: true
  update_when_display_idle: false
  on_draw_end:
    - component.update: magtag_epaper
  buffer_size: 100%
  bg_color: white
  widgets:
    - obj:
        x: 16
        y: 16
        width: 96
        height: 240
        bg_color: black
        bg_opa: 100%
        border_width: 0
    - label:
        x: 28
        y: 264
        text: "LVGL"
        text_color: black
