substitutions:
  name: magtag-lvgl-shapes
  friendly_name: MagTag LVGL Shapes

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: adafruit_magtag29_esp32s2
  framework:
    type: arduino

logger:
  hardware_uart: USB_CDC
  level: DEBUG

globals:
  - id: magtag_epaper_refreshed
    type: bool
    restore_value: false
    initial_value: "false"
  - id: magtag_epaper_refresh_count
    type: int
    restore_value: false
    initial_value: "0"

output:
  - platform: gpio
    id: red_led
    pin: GPIO13

interval:
  - interval: 1s
    then:
      - output.turn_on: red_led
      - delay: 500ms
      - output.turn_off: red_led
  - interval: 10s
    then:
      - lambda: ESP_LOGD("main", "ping output; epaper_refresh_count=%d", id(magtag_epaper_refresh_count));

spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35

display:
  - platform: waveshare_epaper
    id: magtag_epaper
    cs_pin: GPIO8
    dc_pin: GPIO7
    busy_pin: GPIO5
    reset_pin: GPIO6
    model: gdew029t5
    auto_clear_enabled: false
    update_interval: never
    full_update_every: 30

lvgl:
  displays:
    - magtag_epaper
  full_refresh: true
  update_when_display_idle: false
  on_draw_end:
    - if:
        condition:
          lambda: return !id(magtag_epaper_refreshed);
        then:
          - lambda: id(magtag_epaper_refreshed) = true;
          - lambda: id(magtag_epaper_refresh_count) += 1;
          - lambda: ESP_LOGD("main", "requesting one-shot e-paper refresh; epaper_refresh_count=%d", id(magtag_epaper_refresh_count));
          - component.update: magtag_epaper
  update_interval: never
  buffer_size: 100%
  bg_color: black
  widgets:
    - label:
        x: 14
        y: 14
        text: "MagTag LVGL"
        text_color: white
    - obj:
        x: 16
        y: 54
        width: 96
        height: 196
        bg_opa: 0%
        border_width: 6
        border_color: white
    - label:
        x: 28
        y: 262
        text: "RECT"
        text_color: white
