substitutions:
  board: um_feathers3
  flash_size: 16MB
  status_led_gpio: "13"
  rgb_power_gpio: "39"
  rgb_data_gpio: "40"

esphome:
  name: feathers3-rgb-blink
  friendly_name: FeatherS3 RGB Blink
  on_boot:
    priority: 800
    then:
      - lambda: |-
          pinMode(${status_led_gpio}, OUTPUT);
          pinMode(${rgb_power_gpio}, OUTPUT);
          digitalWrite(${rgb_power_gpio}, HIGH);
          rgbLedWrite(${rgb_data_gpio}, 0, 0, 0);

esp32:
  board: ${board}
  flash_size: ${flash_size}
  framework:
    type: arduino

logger:

interval:
  - interval: 500ms
    then:
      - lambda: |-
          static bool on = false;
          on = !on;

          pinMode(${status_led_gpio}, OUTPUT);
          pinMode(${rgb_power_gpio}, OUTPUT);

          digitalWrite(${status_led_gpio}, on ? HIGH : LOW);
          digitalWrite(${rgb_power_gpio}, HIGH);
          rgbLedWrite(${rgb_data_gpio}, on ? 0 : 0, on ? 96 : 0, on ? 0 : 0);

          ESP_LOGD("main", "feathers3 blink %s", on ? "on" : "off");
